# Generated by Django 5.2.14 on 2026-05-23 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '0003_route_current_location_route_dropoff_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driverlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extras', models.JSONField(default=dict)),
                ('log_date', models.DateField()),
                ('driver_number', models.CharField(blank=True, max_length=10, null=True)),
                ('co_driver_name', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_initials', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('trailer_number', models.CharField(blank=True, max_length=50, null=True)),
                ('total_miles_today', models.IntegerField(blank=True, null=True)),
                ('total_mileage_today', models.IntegerField(blank=True, null=True)),
                ('operating_center_name_address', models.CharField(blank=True, max_length=50, null=True)),
                ('total_off_duty_time', models.IntegerField(blank=True, null=True)),
                ('total_sleeper_time', models.IntegerField(blank=True, null=True)),
                ('total_driving_time', models.IntegerField(blank=True, null=True)),
                ('total_on_duty_time', models.IntegerField(blank=True, null=True)),
                ('shipper', models.CharField(blank=True, max_length=50, null=True)),
                ('commodity', models.CharField(blank=True, max_length=50, null=True)),
                ('load_no', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
            ],
            options={
                'db_table': 'driverlog',
            },
        ),
    ]
