# Generated by Django 5.2.14 on 2026-05-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlog',
            name='driver_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
