# Generated by Django 5.2.14 on 2026-05-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverlog', '0002_driverlog_driver_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlog',
            name='driver_name',
        ),
    ]
