# Generated by Django 5.2.14 on 2026-05-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverlog', '0003_remove_driverlog_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlog',
            name='total_driving_time',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverlog',
            name='total_mileage_today',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverlog',
            name='total_miles_today',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverlog',
            name='total_off_duty_time',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverlog',
            name='total_on_duty_time',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverlog',
            name='total_sleeper_time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
