# Generated by Django 5.2.14 on 2026-05-23 02:33

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extras', models.JSONField(default=dict)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('dropoff_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'route',
            },
        ),
    ]
