# Generated by Django 5.2.14 on 2026-05-23 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='route',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='route',
            name='pickup_location',
        ),
    ]
